version: '3.8'
services:
  proxy:
    build: ./nginx
    ports:
    - "8080:80"
    networks:
      - new
  webapp:
    build: ./cloud-app
    networks:
      - new
    depends_on: 
      - db 
    restart: on-failure
    environment:
    - CONNECTION_STRING=Server=db;Database=CloudApp;Uid=user1;Pwd=user1; 
  db:
    image: mysql:latest
    environment: 
    - MYSQL_DATABASE=CloudApp
    - MYSQL_ROOT_PASSWORD=myPass
    - MYSQL_USER=user1
    - MYSQL_PASSWORD=user1
    networks:
      - new
    volumes:
      - dbdata:/var/lib/mysql
networks:
  new:
volumes:
  dbdata:
